apiVersion: oisp.org/v1
kind: BeamService
metadata:
  name: beam-service
spec:
  entryClass: "org.oisp.services.ComponentSplitter"
  args:
    runner: FlinkRunner
    streaming: "true"
  package:
    url: "https://arkocal.rocks/csb.jar"
